export const RECENT_RECIPES_REQUESTED_ASYNC = 'RECENT_RECIPES_REQUESTED_ASYNC';
export const RECENT_RECIPES_REQUESTED = 'RECENT_RECIPES_REQUESTED';
export const ADD_RECIPE_ASYNC = 'ADD_RECIPE_ASYNC';
export const ADD_RECIPE = 'ADD_RECIPE';
